obs_horizon: 2
act_horizon: 8
pred_horizon: 16

diffusion_prediction_type: 'sample'  # 'epsilon' or 'sample'，"v_prediction"
scheduler_clip_sample: True
num_diffusion_iters: 100
diffusion_step_embed_dim: 64
unet_dims: [128, 256, 512] #[16, 32, 64]
hier_num_levels: 1  # 1=平铺, 2=根 vs 末端, 3+=更多层
hier_context_mode: parent_only   # or 'parent_only','all_lower'